### ISSUE TITLE
[FEATURE] Orthognalization on the complex object directly

### ISSUE THREAD

**Issue by ewbellec** [clatlan/cdiutils#22]
This is my scipy version : 
(devel.p9) bellec@p9-01:~$ pip show scipy
Name: scipy
Version: 1.7.1
Summary: SciPy: Scientific Library for Python
Home-page: https://www.scipy.org
Author:
Author-email:
License: BSD
Location: /home/esrf/favre/dev/devel.p9/lib/python3.8/site-packages
Requires: numpy
Required-by: bcdi, gwaihir, lmfit, nabu, PyNX, scikit-image, scikit-learn, xraydb, xrayutilities

My code for the object orthognalization (where obj is the complex object): 
from scipy.interpolate import RegularGridInterpolator
def real_space_orthogonalization(obj, file_ref,
                                 voxel_sizes_cubic=False,
                                 final_roi = True, final_centering = True,
                                 verbose = True, plot=False):
    
    R, B_real_inv = compute_positions_inverse_matrix(file_ref, obj, plot=False)

    # No need to interpolate far outside the object
    roi = automatic_object_roi(obj,plot=False)
    R = R[:,roi[0]:roi[1], roi[2]:roi[3],roi[4]:roi[5]]

    # Create interpolation function
    rgi = RegularGridInterpolator(
        (
            np.arange(-obj.shape[0]//2, obj.shape[0]//2, 1),
            np.arange(-obj.shape[1]//2, obj.shape[1]//2, 1),
            np.arange(-obj.shape[2]//2, obj.shape[2]//2, 1),
        ),
        obj,
        method="linear",
        bounds_error=False,
        fill_value=0,
    )

    # Compute automatic interpolation voxel sizes
    voxel_sizes = compute_automatic_voxel_sizes(file_ref)
    if voxel_sizes_cubic:
        print('force voxel size to be the same along all direction')
        voxel_sizes = np.ones(3) * min(voxel_sizes)
    print('voxel size (Angstrom) : ', voxel_sizes)

    # Calculate the "indices" matrix to interpolate
    M = compute_matrix_to_interpolate(R, B_real_inv, voxel_sizes)

    obj_ortho = rgi((M[0],M[1],M[2]), method='linear')

    if final_centering:
        center_object(obj_ortho)

    if final_roi:
        roi = automatic_object_roi(obj_ortho,plot=False)
        obj_ortho = obj_ortho[roi[0]:roi[1], roi[2]:roi[3], roi[4]:roi[5]]

    if plot:
        plot_2D_slices_middle(obj, fig_title='before orthogonalization', fw=3)
        plot_2D_slices_middle(obj_ortho, fig_title='after orthogonalization (uncropped)', fw=3, crop=False,
                              voxel_sizes=voxel_sizes)
    return obj_ortho, voxel_sizes

Your code : 
    def __call__(self, data: np.ndarray) -> np.ndarray:
        """
        Wrap function to execute the interpolation as if the instance of
        Interpolator3D was a callable.
        """
        rgi = RegularGridInterpolator(
            (
                np.arange(-data.shape[0]//2, data.shape[0]//2, 1),
                np.arange(-data.shape[1]//2, data.shape[1]//2, 1),
                np.arange(-data.shape[2]//2, data.shape[2]//2, 1),
            ),
            data,
            method="linear",
            bounds_error=False,
            fill_value=0,
        )

        # find the interpolated value of the grid which was defined in the 
        # target space and then rotated to the original space
        interpolated_data = rgi(
            np.concatenate(
                (
                    self.target_grid_in_original_space[0].reshape(
                        (1, self.target_grid_in_original_space[0].size)
                    ),
                    self.target_grid_in_original_space[1].reshape(
                        (1, self.target_grid_in_original_space[1].size)
                    ),
                    self.target_grid_in_original_space[2].reshape(
                        (1, self.target_grid_in_original_space[2].size)
                    )
                )
            ).transpose()
        )

        # reshape the volume back to its original shape, thus each voxel 
        # goes back to its initial position
        interpolated_data = interpolated_data.reshape(
            (self.extents[0], self.extents[1], self.extents[2])
        ).astype(interpolated_data.dtype)

        return interpolated_data

I don't understand why yours wouldn't work on complex object. 
Maybe it does, but we talked about it and I don't remember exactly what was the conclusion. Maybe doing module and phase separately is better for the surface pixels? (The surface strain is not really important for my own BCDI data). You might have done this module and phase separation on purpose.

**Comment by ewbellec** [comment]
Sorry for the terrible formatting of the functions, can't get it clean

**Comment by clatlan** [comment]
Resolved
