### ISSUE TITLE
[Extended support]

### ISSUE THREAD

**Issue by DSimonne** [clatlan/cdiutils#64]
I am working to have support for `cdiutils` on the `engaging` MIT cluster.

**Comment by clatlan** [comment]
If you have a gpu available, use Vincent's script to make your env/install pynx, then just pip install cdiutils

**Comment by DSimonne** [comment]
I have to submit batch jobs like you on the p9 cluster so I need to figure that out

**Comment by clatlan** [comment]
Oh nice, I see.
So, on the local machine: cdiutils, on the p9: pynx. Then, you have to make your own .slurm file to meet your requirements (config file to handle number of nodes etc + how to load the pynx env, see: [template](https://github.com/clatlan/cdiutils/blob/master/cdiutils/process/pynx-id01cdi_template.slurm). 

I am currently working on a more generic way to handle the phasing, see the commented code block, so it can handle every type of config (phasing on gpu/local machine/ subprocess etc.) See [phase retrieval method](https://github.com/clatlan/cdiutils/blob/d957475c0c774a4bf039d88b4f4992546b22fa28/cdiutils/process/pipeline.py#L329)

**Comment by DSimonne** [comment]
Engaging does not offer proper support of GPU, switching to NERSC
