### ISSUE TITLE
Support perlmutter cluster at NERSC

### ISSUE THREAD

**Issue by DSimonne** [clatlan/cdiutils#68]
I am working on it, should be ok by the end of the week hopefully

**Comment by DSimonne** [comment]
https://docs.nersc.gov/systems/perlmutter/architecture/

**Comment by DSimonne** [comment]
For the mode analysis, you don't ask for specific resources after remote connection, in contrast with the phase retrieval. Should I just keep working that way or do you want to make a sbatch form ? 


```python
if machine:
    print(f"[INFO] Remote connection to machine '{machine}'requested.")
    if user is None:
        user = os.environ["USER"]
        print(f"user not provided, will use '{user}'.")
    if key_file_path is None:
        key_file_path = os.environ["HOME"] + "/.ssh/id_rsa"
        print(
            f"key_file_path not provided, will use '{key_file_path}'."
        )

    pretty_print(
        f"[INFO] Running mode decomposition on machine '{machine}'"
        f"({self.sample_name}, S{self.scan})"
    )
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(
        hostname=machine,
        username=user,
        pkey=paramiko.RSAKey.from_private_key_file(key_file_path)
    )

    _, stdout, stderr = client.exec_command(run_command)
    # read the standard output, decode it and print it
    formatted_stdout = stdout.read().decode("utf-8")
    formatted_stderr = stderr.read().decode("utf-8")
    print("[STDOUT FROM SSH PROCESS]\n")
    print(formatted_stdout)
    print("[STDERR FROM SSH PROCESS]\n")
    print(formatted_stderr)

    if stdout.channel.recv_exit_status():
        raise RuntimeError(
            f"Error pulling the remote runtime {stderr.readline()}")
    client.close()
```

At NERSC, you login directly on the cluster but you need to ask for resources for each job, kind of like at slurm-devel at the ESRF. 

In general, I am thinking of just making one line commands with `srun` because the slurm job file is not very complicated, but is is more 'clean' with the sbatch.

**Comment by DSimonne** [comment]
I think this part of the script should be written in a different way to support different computing clusters.

For now either you use a machine (slurm-nice-devel only) or not. If you don't, it looks at your nodename and adapts the script, for example you can set machine to None but still use the script with the p9, even though technically I think that when you submit a job via slurm you submit it to the p9 ?

I think it would be best to divide first between either submitting jobs with slurm, or working locally, especially because at nersc there are many different possibilities and it's a bit tricky to fit.

![image](https://github.com/user-attachments/assets/f0efb252-c6e6-4148-a2fc-eb4a7d25e945)

**Comment by DSimonne** [comment]
I also think there is a pb in the slurm file:

```bash
#!/bin/bash -l
#SBATCH --partition=gpu,p9gpu
#SBATCH --nodes=$number_of_nodes
#SBATCH --ntasks-per-node=2
#SBATCH --ntasks=4
#SBATCH --gres=gpu:2
#SBATCH --time=00:10:00
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-gpu=4G
#SBATCH --output=%x-%j.out
```

You can specify the number of nodes in the code, but there is always only 2 tasks per node and 4 tasks in total, so having more than 2 nodes is not usefull no ?

**Comment by clatlan** [comment]
The way the connection to GPU nodes is done will probably change in the future. I will probably use pyslurmutils. I am not sure that I have understood everything, are you referring to the phase retrieval or the mode decomposition?

**Comment by DSimonne** [comment]
OK I did not know about pyslurmutils, I was referring to how the different machines are organised for PR, which is not the same as for the modes decomposition either
